routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostCommentController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\PostTagController;
use App\Http\Controllers\UserCommentController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class,'home'])->name('home');
Route::get('/contact', [HomeController::class,'contact'])->name('contact');
Route::get('/secret',[HomeController::class,'secret'])->name('secret')->middleware(['can:home.secret']);
Route::resource('posts', PostController::class);

Auth::routes();
Route::get('/posts/tag/{tag}',[PostTagController::class,'index'])->name('posts.tags.index');
Route::resource('posts.comments',PostCommentController::class)->only(['index','store']);
Route::resource('users',UserController::class)->only(['show','edit','update']);
//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('users.comments',UserCommentController::class)->only(['store']);
Route::get('mailable',function (){
    $comment=\App\Models\Comment::find(1);
    return new \App\Mail\CommentPostedMarkdown($comment);
});

resources/views/contact.blade.php
@extends('layout')

@section('content')
<h1>Contact</h1>
<p>Hello this is contact!</p>
    @can('home.secret')
        <a href="{{ route('secret') }}">Go to special contact details</a>
    @endcan
@endsection

resources/views/home.blade.php
@extends('layout')

@section('content')
    <h1>{{ __('messages.welcome') }}</h1>
    <h1>@lang('messages.welcome')</h1>

    <p>{{ __('messages.example_with_value',['name'=>'John']) }}</p>
    <p>{{ trans_choice('messages.plural',0) }}</p>
    <p>{{ trans_choice('messages.plural',1) }}</p>
    <p>{{ trans_choice('messages.plural',3) }}</p>
    <p>{{ __('Welcome to Laravel!') }}</p>
    <p>{{ __('Hello :name',['name'=>'Oliver']) }}</p>
    <p>This is the content of the main page!</p>
    <p></p>
@endsection

resources/views/layout.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto ">
                    <!-- Authentication Links -->
                    <a class="nav-link p-2 " href="{{ route('home') }}">{{__('Home')}}</a>
                    <a class="nav-link p-2" href="{{ route('contact') }}">{{__('Contact')}}</a>
                    <a class="nav-link p-2 " href="{{ route('posts.index') }}">{{__('Blog Posts')}}</a>
                    <a class="nav-link p-2 " href="{{ route('posts.create') }}">{{__('Add')}}</a>
                    @guest
                        @if (Route::has('login'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                        @endif

                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('users.show',['user'=>Auth::user()->id]) }}">{{ __('Profile') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('users.edit',['user'=>Auth::user()->id]) }}">{{ __('Edit Profile') }}</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }}
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <div class="container py-4">
        @if(session()->has('status'))
            <p style="color: green">
                {{ session()->get('status') }}
            </p>
        @endif

            @yield('content')
    </div>
</div>
</body>
</html>

resources/views/secret.blade.php
@extends('layout')

@section('content')
    <h1>Secret Page!</h1>
    <p>This is a secret email secret@laravel.test</p>

@endsection