routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostCommentController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\PostTagController;
use App\Http\Controllers\UserCommentController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class,'home'])->name('home');
Route::get('/contact', [HomeController::class,'contact'])->name('contact');
Route::get('/secret',[HomeController::class,'secret'])->name('secret')->middleware(['can:home.secret']);
Route::resource('posts', PostController::class);

Auth::routes();
Route::get('/posts/tag/{tag}',[PostTagController::class,'index'])->name('posts.tags.index');
Route::resource('posts.comments',PostCommentController::class)->only(['index','store']);
Route::resource('users',UserController::class)->only(['show','edit','update']);
//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('users.comments',UserCommentController::class)->only(['store']);
Route::get('mailable',function (){
    $comment=\App\Models\Comment::find(1);
    return new \App\Mail\CommentPostedMarkdown($comment);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;


class User extends Authenticatable
{
    use Notifiable;
    use HasFactory;
    public const LOCALES=[
        'en'=>'English',
        'es'=>'Espanol',
        'de'=>'Deutsch'
    ];
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token','email','email_verified_at','created_at','updated_at','is_admin','locale'
    ];
    public function blogPosts(){
        return $this->hasMany(BlogPost::class);
    }
    public function comments(){
        return $this->hasMany(Comment::class);
    }
    public function commentsOn(){
        return $this->morphMany(Comment::class,'commentable');
    }
    public function image(){
        return $this->morphOne(Image::class,'imageable');
    }
    public function scopeWithMostBlogPosts(Builder $query)
    {
        return $query->withCount('blogPosts')->orderBy('blog_posts_count', 'desc');
    }
    public function scopeWithMostBlogPostsLastMonth(Builder $query)
    {
        return $query->withCount(['blogPosts' => function (Builder $query) {
            $query->whereBetween(static::CREATED_AT, [now()->subMonths(1), now()]);
        }])->having('blog_posts_count', '>=', 2)
            ->orderBy('blog_posts_count', 'desc');
    }
    public function scopeThatHasCommentedOnPost(Builder $query, BlogPost $post)
    {
        return $query->whereHas('comments', function ($query) use ($post) {
            return $query->where('commentable_id', '=', $post->id)
                ->where('commentable_type', '=', BlogPost::class);
        });
    }
    public function scopeThatIsAnAdmin(Builder $query){
        return $query->where('is_admin',true);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;


use App\Facades\CounterFacade;
use App\Http\Requests\UpdateUser;
use App\Models\Image;
use App\Models\User;

use Illuminate\Http\Request;

class UserController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
        $this->authorizeResource(User::class, 'user');


    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    public function show(User $user)
    {
        return view('users.show', ['user' => $user,
            'counter'=>CounterFacade::increment("user-{$user->id}")]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
        return view('users.edit', ['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUser $request, User $user)
    {
        //
        if ($request->hasFile('avatar')) {
            $path = $request->file('avatar')->store('avatars');

            if ($user->image) {
                $user->image->path = $path;
                $user->image->save();
            } else {
                $user->image()->save(
                    Image::make(['path' => $path])
                );
            }
        }
        $user->locale = $request->get('locale');
        $user->save();
        return redirect()
            ->back()
            ->withStatus('Profile image was updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/users/edit.blade.php
@extends('layout')
@section('content')
    <form action="{{ route('users.update',['user'=>$user->id]) }}" method="POST" enctype="multipart/form-data" class="form-horizontal">
@csrf
        @method('PUT')
        <div class="row">
            <div class="col-4">
                <img src="{{ $user->image ? $user->image->url() :  '' }}" class="img-thumbnail avatar" />

                <div class="card mt-4">
                    <div class="card-body">
                        <h6>{{ __('Upload a different photo') }}</h6>
                        <input class="form-control-file" type="file" name="avatar" />
                    </div>
                </div>
            </div>
            <div class="col-8">

                <div class="form-group">
                    <label>Name:</label>
                    <input class="form-control" value="" type="text" name="name" />
                </div>
                <div class="form-group">
                    <label>{{ __('Language:') }}</label>
                    <select class="form-control" name="locale">
                        @foreach(App\Models\User::LOCALES as $locale=>$label)
                            <option value="{{ $locale }}" {{ $user->locale !== $locale ?: 'selected'}}> {{ $label }}</option>
                        @endforeach
                    </select>
                </div>
                <x-errors></x-errors>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Save Changes" />
                </div>
            </div>
        </div>
    </form>
    @endsection

resources/views/users/show.blade.php
@extends('layout')

@section('content')
    <div class="row">
        <div class="col-4">
            <img src="{{ $user->image ? $user->image->url() :  '' }}" class="img-thumbnail avatar" />
        </div>
        <div class="col-8">
            <h3>{{ $user->name }}</h3>
            <p>Currently viewed by {{$counter }} other users</p>
            <x-comment-form>
                @slot('route',route('users.comments.store',['user'=>$user->id]))
            </x-comment-form>
            <x-comment-list>
                @slot('comments',$user->commentsOn)
            </x-comment-list>
        </div>

    </div>
@endsection