routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostCommentController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\PostTagController;
use App\Http\Controllers\UserCommentController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class,'home'])->name('home');
Route::get('/contact', [HomeController::class,'contact'])->name('contact');
Route::get('/secret',[HomeController::class,'secret'])->name('secret')->middleware(['can:home.secret']);
Route::resource('posts', PostController::class);

Auth::routes();
Route::get('/posts/tag/{tag}',[PostTagController::class,'index'])->name('posts.tags.index');
Route::resource('posts.comments',PostCommentController::class)->only(['index','store']);
Route::resource('users',UserController::class)->only(['show','edit','update']);
//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('users.comments',UserCommentController::class)->only(['store']);
Route::get('mailable',function (){
    $comment=\App\Models\Comment::find(1);
    return new \App\Mail\CommentPostedMarkdown($comment);
});

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Contracts\CounterContract;
use App\Events\BlogPostPosted;
use App\Facades\CounterFacade;
use App\Models\BlogPost;
use App\Models\Image;

use Illuminate\Http\Request;
use App\Http\Requests\StorePost;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;

use Illuminate\Support\Facades\Storage;


class PostController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth')
            ->only(['create', 'store', 'edit', 'update', 'destroy']);

    }

    public function index()
    {
        return view('posts.index', [
            'posts' => Auth::check() && Auth::user()->is_admin ?
                BlogPost::withTrashed()->latestWithRelations()->get()
                : BlogPost::latestWithRelations()->get(),
        ]);
    }


    public function show($id)
    {
        $blogPost = Cache::tags(['blog-post'])->remember("blog-post-{$id}", 60, function () use ($id) {
            return BlogPost::with('comments', 'tags', 'user', 'comments.user')->findOrFail($id);
        });

//        return view('posts.show', ['post' => BlogPost::with([
//            'comments' => function ($query) {
//                return $query->latest();
//            }
//        ])->findOrFail($id)]);
//       $counter=resolve(Counter::class);
//        dd($this->counter);
        return view('posts.show', [
            'post' => $blogPost,
            'counter' => CounterFacade::increment("blog-post-{$id}",['blog-post']),
        ]);
    }

    public function create()
    {
        return view('posts.create');
    }

    public function store(StorePost $request)
    {
        $validatedData = $request->validated();
        $validatedData['user_id'] = Auth::id();
        $blogPost = BlogPost::create($validatedData);
        if ($request->hasFile('thumbnail')) {
            $path = $request->file('thumbnail')->store('thumbnails');
            $blogPost->image()->save(
                Image::make(['path' => $path])
            );
        }
        event(new BlogPostPosted($blogPost));

        $request->session()->flash('status', 'Blog post was created!');

        return redirect()->route('posts.show', ['post' => $blogPost->id]);
    }

    public function edit($id)
    {
        $post = BlogPost::findOrFail($id);
//        if(Gate::denies('update-post',$post)){
//            abort(403,'You cannot edit this post');
//        }
        $this->authorize($post);
        return view('posts.edit', ['post' => $post]);
    }

    public function update(StorePost $request, $id)
    {
        $post = BlogPost::findOrFail($id);
//        if(Gate::denies('update-post',$post)){
//            abort(403,'You cannot edit this post');
//        }
        $this->authorize($post);
        $validatedData = $request->validated();

        $post->fill($validatedData);
        if ($request->hasFile('thumbnail')) {
            $path = $request->file('thumbnail')->store('thumbnails');
            if ($post->image) {
                Storage::delete($post->image->path);
                $post->image->path = $path;
                $post->image->save();
            } else {
                $post->image()->save(
                    Image::make(['path' => $path])
                );
            }
        }
        $post->save();
        $request->session()->flash('status', 'Blog post was updated!');

        return redirect()->route('posts.show', ['post' => $post->id]);
    }

    public function destroy(Request $request, $id)
    {
        $post = BlogPost::findOrFail($id);
//        if(Gate::denies('update-post',$post)){
//            abort(403,'You cannot delete this post');
//        }
        $this->authorize($post);
        $post->delete();

        // BlogPost::destroy($id);

        $request->session()->flash('status', 'Blog post was deleted!');

        return redirect()->route('posts.index');
    }
}

resources/views/posts/_activity.blade.php
<div class="container">
    <div class="row">
        <x-card title="Most Active Last Month">
            @slot('subtitle')
                What people are currently talking about
            @endslot
            @slot('items')
                @foreach ($mostCommented as $post)
                    <li class="list-group-item">
                        <a href="{{ route('posts.show', ['post' => $post->id]) }}">
                            {{ $post->title }}
                        </a>
                    </li>
                @endforeach
            @endslot
        </x-card>
    </div>

    <div class="row mt-4">
        <x-card title="Most Active">
            @slot('subtitle','Users with most posts written')

            @slot('items',collect($mostActive)->pluck('name'))
        </x-card>
    </div>
    <div class="row mt-4">
        <x-card title="Most Active Last Month">
            @slot('subtitle','Users with most posts written in the month')


            @slot('items', collect($mostActiveLastMonth)->pluck('name'))
        </x-card>
    </div>

</div>

resources/views/posts/_form.blade.php
<div class="form-group">
    <label>Title</label>
    <input type="text" name="title" class="form-control"
        value="{{ old('title', $post->title ?? null) }}"/>
</div>

<div class="form-group">
    <label>Content</label>
    <input type="text" name="content" class="form-control"
        value="{{ old('content', $post->content ?? null) }}"/>
</div>

<div class="form-group">
    <label>Thumbnail</label>
    <input type="file" name="thumbnail" class="form-control-file"/>
</div>
<x-errors></x-errors>

resources/views/posts/create.blade.php
@extends('layout')

@section('content')
    <form method="POST" action="{{ route('posts.store') }}" enctype="multipart/form-data">
        @csrf

        @include('posts._form')

        <button type="submit" class="btn btn-primary btn-block">Create!</button>
    </form>
@endsection

resources/views/posts/edit.blade.php
@extends('layout')

@section('content')
    <form method="POST"
          action="{{ route('posts.update', ['post' => $post->id]) }}" enctype="multipart/form-data">
        @csrf
        @method('PUT')

        @include('posts._form')

        <button type="submit" class="btn btn-primary btn-block">Update!</button>
    </form>
@endsection

resources/views/posts/index.blade.php
@extends('layout')

@section('content')
    <div class="row">
        <div class="col-8">
            @forelse ($posts as $post)
                <p>
                <h3>
                    @if($post->trashed())
                        <del>
                            @endif
                            <a class="{{ $post->trashed() ? 'text-muted' : '' }}"
                               href="{{ route('posts.show', ['post' => $post->id]) }}">{{ $post->title }}</a>
                            @if($post->trashed())
                        </del>
                    @endif
                </h3>


                <x-updated>
                    @slot('date',$post->created_at)
                    @slot('name',$post->user->name)
                    @slot('userId',$post->user->id)
                </x-updated>

            <x-tags>
                @slot('tags',$post->tags)

            </x-tags>
             <p> {{ trans_choice('messages.comments',$post->comments_count)  }}</p>

                @auth
                    @can('update', $post)
                        <a href="{{ route('posts.edit', ['post' => $post->id]) }}"
                           class="btn btn-primary">
                            Edit
                        </a>
                    @endcan
                @endauth
                {{-- @cannot('delete', $post)
                    <p>You can't delete this post</p>
                @endcannot --}}
                @auth
                    @if(!$post->trashed())
                        @can('delete', $post)
                            <form method="POST" class="fm-inline"
                                  action="{{ route('posts.destroy', ['post' => $post->id]) }}">
                                @csrf
                                @method('DELETE')

                                <input type="submit" value="Delete!" class="btn btn-primary"/>
                            </form>
                        @endcan
                    @endif
                @endauth

            @empty
                <p>No blog posts yet!</p>
            @endforelse
        </div>
        <div class="col-4">
            @include('posts._activity')
        </div>
    </div>
@endsection('content')

resources/views/posts/show.blade.php
@extends('layout')

@section('content')
    <div class="row">
        <div class="col-8">
            @if($post->image)
                <div
                    style="background-image: url('{{ $post->image->url() }}'); min-height: 500px; color: white; text-align: center; background-position: center; background-attachment: fixed;">
                    <h1 style="padding-top: 100px; text-shadow: 1px 2px #000">
                        @else
                            <h1>
                                @endif
                                {{ $post->title }}
                                <x-badge>
                                    @slot('show',now()->diffInMinutes($post->created_at) < 30)
                                    Brand New Post!
                                </x-badge>
                                @if($post->image)

                            </h1>
                </div>
                @else
                </h1>
            @endif
            <p>{{ $post->content }}</p>
            {{--            <img src="{{ Storage::url($post->image->path) }}" alt="">--}}
            {{--            <img src="{{ $post->image->url() }}" alt="">--}}
            <x-updated>
                @slot('date',$post->created_at )
                @slot('name',$post->user->name )
            </x-updated>

            <x-updated>
                @slot('date',$post->updated_at )
                Updated
            </x-updated>

            <x-tags>
                @slot('tags',$post->tags)
            </x-tags>
            <p> {{ trans_choice('messages.people.reading',$counter)  }}</p>
            <h4>Comments</h4>
         <x-comment-form>
             @slot('route',route('posts.comments.store',['post'=>$post->id]))
         </x-comment-form>
            <x-comment-list>
                @slot('comments',$post->comments)
            </x-comment-list>
        </div>
        <div class="col-4">
            @include('posts._activity')
        </div>
    </div>
@endsection('content')